### ISSUE TITLE
stiximport does not work

### ISSUE THREAD

**Issue by davidonzo** [MISP/misp-modules#103]
It seems there's a problem with "stiximport" module. I tried both on a custom installation (Debian 8) and downloading the virtual image. Latest MISP version available.

The error is:

##################
2017-02-14 12:17:41,473 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter/converters/convert.py", line 75, in load_stix
    stix_package = STIXPackage.from_json(stix)
  File "/usr/local/lib/python3.4/dist-packages/mixbox/entities.py", line 468, in from_json
    d = json.load(json_doc)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/import_mod/stiximport.py", line 35, in handler
    pkg = stix.load_stix(package)
  File "/usr/local/lib/python3.4/dist-packages/pymisp/tools/stix.py", line 17, in load_stix
    stix = convert.load_stix(stix)
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter/converters/convert.py", line 106, in load_stix
    return load_stix(f)
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter/converters/convert.py", line 76, in load_stix
    except (TypeError, json.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter/converters/convert.py", line 75, in load_stix
    stix_package = STIXPackage.from_json(stix)
  File "/usr/local/lib/python3.4/dist-packages/mixbox/entities.py", line 468, in from_json
    d = json.load(json_doc)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/import_mod/stiximport.py", line 35, in handler
    pkg = stix.load_stix(package)
  File "/usr/local/lib/python3.4/dist-packages/pymisp/tools/stix.py", line 17, in load_stix
    stix = convert.load_stix(stix)
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter/converters/convert.py", line 106, in load_stix
    return load_stix(f)
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter/converters/convert.py", line 76, in load_stix
    except (TypeError, json.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
##################

I received the same error in both installations.

Any suggestion?

**Comment by Rafiot** [comment]
It seems borken on python 3.4. I'm working on it, give me an hour.

Sorry for that.

**Comment by Rafiot** [comment]
Fixed: https://travis-ci.org/MISP/misp-modules/builds/200410960

You will need to upgrade the misp-stix library:

```
pip install -U git+https://github.com/MISP/MISP-STIX-Converter.git#egg=misp_stix_converter
```

**Comment by davidonzo** [comment]
Thank you very much, and sorry for the delay of my feedback.

I can confirm the import now works fine!
This kind of support give to MISP the real value!
