### ISSUE TITLE
Official DomainTools Modules Break MISP-MODULES

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/misp-modules#171]
After the latest commits, just updated today, the modules here: https://github.com/DomainTools/domaintools_misp
 break misp-modules giving the error below:

```
ERROR:tornado.application:Uncaught exception GET /modules (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:6666', method='GET', uri='/modules', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 167, in get
    x['mispattributes'] = mhandlers[module].introspection()
AttributeError: module 'expansion.historic' has no attribute 'introspection'
ERROR:tornado.access:500 GET /modules (127.0.0.1) 3.36ms
```
Using this command to start the modules: sudo -u www-data misp-modules -m domaintools_misp &

It was working until the git pull on misp-modules I did today.

**Comment by robertnixon2003** [comment]
It was an API issue.
