### ISSUE TITLE
VirusTotal Module Error for ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/misp-modules#186]
Getting an error on the MISP modules now:

```
2018-05-10 14:45:49,438 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/modules/expansion/virustotal.py", line 31, in handler
    limit = int(q["config"].get("event_limit", 5))
ValueError: invalid literal for int() with base 10: ''
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/modules/expansion/virustotal.py", line 31, in handler
    limit = int(q["config"].get("event_limit", 5))
ValueError: invalid literal for int() with base 10: ''
```
This is when running the VirusTotal module/enrichment on a SHA256 hash.

It seems to just be the VirusTotal module

When I set the a limit in the config for the Virus Total module I get a different error:
```
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/modules/expansion/virustotal.py", line 48, in handler
    r["results"] += getHash(q['sha256'], key)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/modules/expansion/virustotal.py", line 65, in getHash
    req = req.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by robertnixon2003** [comment]
This error was due to the fact that we had consumed all of our private API key quota.

**Comment by adulau** [comment]
Thanks for the feedback. Maybe we need to fix the error message to make it more meaningful.
