### ISSUE TITLE
[centos7] misp-modules - WARNING - MISP modules sigma_queries failed due to name 'ModuleNotFoundError' is not defined

### ISSUE THREAD

**Issue by juju4** [MISP/misp-modules#216]
Travis execution of ansible role. 
Installation play OK
Verification NOK

Good, a month ago
https://travis-ci.org/juju4/ansible-MISP/jobs/402641657
pip3: yara-1.7.7.tar.gz, sigmatools-0.5-py3
```misp-modules -t```` OK

Warning/Error, currently
https://travis-ci.org/juju4/ansible-MISP/jobs/413562348
pip3: yara-1.7.7.tar.gz, sigmatools-0.6-py3
```
# misp-modules -t
Failed to import '/usr/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin;/usr/lib
yara is missing, use 'pip3 install yara' to install it.
name 'ModuleNotFoundError' is not defined
2018-08-11 12:34:53,578 - misp-modules - INFO - Launch MISP modules server from current directory.
2018-08-11 12:34:53,581 - misp-modules - INFO - Helpers failed cache.py due to Redis not running or not installed. Helper will be disabled.
2018-08-11 12:34:53,584 - misp-modules - INFO - MISP modules eupi imported
2018-08-11 12:34:53,586 - misp-modules - INFO - MISP modules threatcrowd imported
2018-08-11 12:34:53,587 - misp-modules - INFO - MISP modules countrycode imported
2018-08-11 12:34:53,589 - misp-modules - INFO - MISP modules dbl_spamhaus imported
2018-08-11 12:34:53,592 - misp-modules - INFO - MISP modules securitytrails imported
2018-08-11 12:34:53,593 - misp-modules - INFO - MISP modules ipasn imported
2018-08-11 12:34:53,594 - misp-modules - INFO - MISP modules wiki imported
2018-08-11 12:34:53,596 - misp-modules - INFO - MISP modules farsight_passivedns imported
2018-08-11 12:34:53,597 - misp-modules - INFO - MISP modules rbl imported
2018-08-11 12:34:53,598 - misp-modules - INFO - MISP modules crowdstrike_falcon imported
2018-08-11 12:34:53,599 - misp-modules - INFO - MISP modules sigma_syntax_validator imported
2018-08-11 12:34:53,599 - misp-modules - INFO - MISP modules hashdd imported
2018-08-11 12:34:53,600 - misp-modules - INFO - MISP modules otx imported  
2018-08-11 12:34:53,601 - misp-modules - INFO - MISP modules shodan imported
2018-08-11 12:34:53,602 - misp-modules - INFO - MISP modules vmray_submit imported
2018-08-11 12:34:53,603 - misp-modules - INFO - MISP modules dns imported  
2018-08-11 12:34:53,608 - misp-modules - WARNING - MISP modules sigma_queries failed due to name 'ModuleNotFoundError' is not defined
2018-08-11 12:34:53,609 - misp-modules - INFO - MISP modules cve imported  
2018-08-11 12:34:53,610 - misp-modules - INFO - MISP modules circl_passivedns imported
2018-08-11 12:34:53,611 - misp-modules - INFO - MISP modules vulndb imported
```

checking manually
```
# python3 -c 'import sigma' 
# python3 -c 'import sigma_queries'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'sigma_queries'
# python3 -c 'import yara'                     
Failed to import '/usr/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin;/usr/lib
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/lib/python3.4/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/lib/python3.4/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 424, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 346, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpcre.so.3: cannot open shared object file: No such file or directory
```

yara issue solved with
```
# ln -s /usr/lib64/libpcre.so.1 /usr/lib64/libpcre.so.3
```

No sigma_queries in upstream https://github.com/Neo23x0/sigma/search?q=sigma_queries&unscoped_q=sigma_queries
found here https://github.com/MISP/misp-modules/blob/73161ad1534505392015476ef3f0e86d5a88e697/misp_modules/modules/expansion/sigma_queries.py

```
# python3 misp_modules/modules/expansion/sigma_queries.py 
Traceback (most recent call last):
  File "misp_modules/modules/expansion/sigma_queries.py", line 5, in <module>
    from sigma.backends import getBackend, BackendOptions
  File "/usr/lib/python3.4/site-packages/sigma/backends.py", line 700
    **min_doc_count
     ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "misp_modules/modules/expansion/sigma_queries.py", line 6, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```

how to fix that?

Thanks

**Comment by adulau** [comment]
@juju4 Sigma needs Python 3.5 or higher... this might be the issue.

**Comment by juju4** [comment]
ah yes. on centos7, that's an issue... community repo or source
maybe a higher warning on python version would be useful.

Thanks for the quick response!

**Comment by adulau** [comment]
Thanks for the feedback. Python 3.6 is not available on CentOS 7?

**Comment by juju4** [comment]
humm. something new.
base centos7 clearly no

but epel has added python36 along python34. don't know why no meta package python3...
https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/
seems from end of last dec: https://lists.fedoraproject.org/archives/list/epel-announce@lists.fedoraproject.org/thread/VLTFSZEQHXBZHHDAKMT4KCQEKPSFV5OS/

but PATH and PYTHONPATH updates needed to use.

Thanks @adulau
