### ISSUE TITLE
VirusTotal Module Failing

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/misp-modules#236]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 155, in handler
    r = query.parse_request(q)
  File "modules/expansion/virustotal.py", line 41, in parse_request
    error = self.input_types_mapping[attribute_type](attribute_value)
  File "modules/expansion/virustotal.py", line 87, in get_hash
    self.get_more_info(req)
  File "modules/expansion/virustotal.py", line 137, in get_more_info
    self.results[((MISP_type,), comment.format(h))].add(data[VT_type])
TypeError: unhashable type: 'list'
```

I am getting the error above no matter the type of attribute I submit to this module. I am using the latest version. MISP version 2.4.95

**Comment by robertnixon2003** [comment]
Also I am using a private key with VTI access.

**Comment by robertnixon2003** [comment]
The module works if using a public key. VT has changed so of the output recently depending on if you are using a premium key or not. We need two modules. One for free keys and one for premium VTI keys.

**Comment by adulau** [comment]
@chrisr3d this was solved? I don't remember.

**Comment by chrisr3d** [comment]
I will try with a private key asap

**Comment by adulau** [comment]
@robertnixon2003 could you share privately with us the JSON query and output? We cannot reproduce it with a public key and private key (VTI).

**Comment by robertnixon2003** [comment]
I could but it seems the module is working again. I am using a private key and I am receiving all the information that I would expect to receive. Maybe this issue was effected by another problem that has since been fixed. Not sure. I do receive a lot more data back from my private key vs. the public key but that is to be expected with Virus Total Intelligence access.
