### ISSUE TITLE
cve_advanced throws error

### ISSUE THREAD

**Issue by StefanKelm** [MISP/misp-modules#323]
Trying to enrich a CVE using the new _cve_advanced_ module throws the following error:

```
2019-08-12T12:10:21.808876+02:00 mist-host misp-modules[1325]: 2019-08-12 12:10:21,808 - misp-modules - ERROR - Something went wrong:
2019-08-12T12:10:21.808891+02:00 mist-host misp-modules[1325]: Traceback (most recent call last):
2019-08-12T12:10:21.808899+02:00 mist-host misp-modules[1325]:   File "/services/inst/misp-modules/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 201, in post
2019-08-12T12:10:21.808908+02:00 mist-host misp-modules[1325]:     response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
2019-08-12T12:10:21.808917+02:00 mist-host misp-modules[1325]:   File "/services/inst/misp-modules/venv/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
2019-08-12T12:10:21.808925+02:00 mist-host misp-modules[1325]:     value = future.result()
2019-08-12T12:10:21.808933+02:00 mist-host misp-modules[1325]:   File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
2019-08-12T12:10:21.808942+02:00 mist-host misp-modules[1325]:     result = self.fn(*self.args, **self.kwargs)
2019-08-12T12:10:21.808950+02:00 mist-host misp-modules[1325]:   File "/services/inst/misp-modules/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
2019-08-12T12:10:21.808958+02:00 mist-host misp-modules[1325]:     response = mhandlers[x['module']].handler(q=jsonpayload)
2019-08-12T12:10:21.808966+02:00 mist-host misp-modules[1325]:   File "modules/expansion/cve_advanced.py", line 114, in handler
2019-08-12T12:10:21.808978+02:00 mist-host misp-modules[1325]:     parser.parse_vulnerability_information()
2019-08-12T12:10:21.808991+02:00 mist-host misp-modules[1325]:   File "modules/expansion/cve_advanced.py", line 55, in parse_vulnerability_information
2019-08-12T12:10:21.809003+02:00 mist-host misp-modules[1325]:     self.__parse_capec(vulnerability_object.uuid)
2019-08-12T12:10:21.809014+02:00 mist-host misp-modules[1325]:   File "modules/expansion/cve_advanced.py", line 73, in __parse_capec
2019-08-12T12:10:21.809022+02:00 mist-host misp-modules[1325]:     capec_object.add_attribute('related-weakness', **attribute)
2019-08-12T12:10:21.809031+02:00 mist-host misp-modules[1325]:   File "/services/inst/misp-modules/venv/src/pymisp/pymisp/mispevent.py", line 1126, in add_attribute
2019-08-12T12:10:21.809039+02:00 mist-host misp-modules[1325]:     attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
2019-08-12T12:10:21.809047+02:00 mist-host misp-modules[1325]:   File "/services/inst/misp-modules/venv/src/pymisp/pymisp/mispevent.py", line 911, in from_dict
2019-08-12T12:10:21.809055+02:00 mist-host misp-modules[1325]:     super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
2019-08-12T12:10:21.809064+02:00 mist-host misp-modules[1325]:   File "/services/inst/misp-modules/venv/src/pymisp/pymisp/mispevent.py", line 193, in from_dict
2019-08-12T12:10:21.809072+02:00 mist-host misp-modules[1325]:     raise NewAttributeError('{} is invalid, type has to be in {}'.format(self.type, (', '.join(self._types))))2019-08-12T12:10:21.809100+02:00 mist-host misp-modules[1325]: pymisp.exceptions.NewAttributeError: weakness is invalid, type has to be in md5, sha1, sha256, filename, pdb, filename|md5, filename|sha1, filename|sha256, ip-src, ip-dst, hostname, domain, domain|ip, email-src, email-dst, email-subject, email-attachment, email-body, float, url, http-method, user-agent, ja3-fingerprint-md5, hassh-md5, hasshserver-md5, regkey, regkey|value, AS, snort, bro, zeek, pattern-in-file, pattern-in-traffic, pattern-in-memory, yara, stix2-pattern, sigma, gene, mime-type, identity-card-number, cookie, vulnerability, attachment, malware-sample, link, comment, text, hex, other, named pipe, mutex, target-user, target-email, target-machine, target-org, target-location, target-external, btc, xmr, iban, bic, bank-account-nr, aba-rtn, bin, cc-number, prtn, phone-number, threat-actor, campaign-name, campaign-id, malware-type, uri, authentihash, ssdeep, imphash, pehash, impfuzzy, sha224, sha384, sha512, sha512/224, sha512/256, tlsh, cdhash, filename|authentihash, filename|ssdeep, filename|imphash, filename|impfuzzy, filename|pehash, filename|sha224, filename|sha384, filename|sha512, filename|sha512/224, filename|sha512/256, filename|tlsh, windows-scheduled-task, windows-service-name, windows-service-displayname, whois-registrant-email, whois-registrant-phone, whois-registrant-name, whois-registrant-org, whois-registrar, whois-creation-date, x509-fingerprint-sha1, x509-fingerprint-md5, x509-fingerprint-sha256, dns-soa-email, size-in-bytes, counter, datetime, cpe, port, ip-dst|port, ip-src|port, hostname|port, mac-address, mac-eui-64, email-dst-display-name, email-src-display-name, email-header, email-reply-to, email-x-mailer, email-mime-boundary, email-thread-index, email-message-id, github-username, github-repository, github-organisation, jabber-id, twitter-id, first-name, middle-name, last-name, date-of-birth, place-of-birth, gender, passport-number, passport-country, passport-expiration, redress-number, nationality, visa-number, issue-date-of-the-visa, primary-residence, country-of-residence, special-service-request, frequent-flyer-number, travel-details, payment-details, place-port-of-original-embarkation, place-port-of-clearance, place-port-of-onward-foreign-destination, passenger-name-record-locator-number, mobile-application-id, cortex, boolean, anonymised
```

**Comment by adulau** [comment]
You are missing the weakness type. Did you update your MISP to the latest version?

**Comment by StefanKelm** [comment]
I see the weakness type (in `app/Model/Attribute.php`, correct?) and we just did a fresh install. Problem remains...

**Comment by adulau** [comment]
Don't forget to update PyMISP too. Sorry I forgot to mention it,

**Comment by StefanKelm** [comment]
No worries, thanks for your help. PyMISP was indeed not on the most current version (at least from within `venv`, since we followed a manual which didn't mention to perform updates inside `venv` as well...  ;) ). However, the error is still there (copying it here again since the version above is not complete):

```
 ERROR:misp-modules:Something went wrong:
 Traceback (most recent call last):
   File "/services/inst/misp-modules/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 201, in post
     response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
   File "/services/inst/misp-modules/venv/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
     value = future.result()
   File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
     result = self.fn(*self.args, **self.kwargs)
   File "/services/inst/misp-modules/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 189, in run_request
     response = mhandlers[x['module']].handler(q=jsonpayload)
   File "modules/expansion/cve_advanced.py", line 114, in handler
     parser.parse_vulnerability_information()
   File "modules/expansion/cve_advanced.py", line 55, in parse_vulnerability_information
     self.__parse_capec(vulnerability_object.uuid)
   File "modules/expansion/cve_advanced.py", line 73, in __parse_capec
     capec_object.add_attribute('related-weakness', **attribute)
   File "/services/inst/misp-modules/venv/src/pymisp/pymisp/mispevent.py", line 1126, in add_attribute
     attribute.from_dict(object_relation=object_relation, **dict(self._default_attributes_parameters, **value))
   File "/services/inst/misp-modules/venv/src/pymisp/pymisp/mispevent.py", line 911, in from_dict
     super(MISPObjectAttribute, self).from_dict(**dict(self, **kwargs))
   File "/services/inst/misp-modules/venv/src/pymisp/pymisp/mispevent.py", line 193, in from_dict
     raise NewAttributeError('{} is invalid, type has to be in {}'.format(self.type, (', '.join(self._types))))
 pymisp.exceptions.NewAttributeError: weakness is invalid, type has to be in md5, sha1, sha256, filename, pdb, filename|md5, filename|sha1, filename|sha256, ip-src, ip-dst, hostname, domain, domain|ip, email-src, email-dst, email-subject, email-attachment, email-body, float, url, http-method, user-agent, ja3-fingerprint-md5, hassh-md5, hasshserver-md5, regkey, regkey|value, AS, snort, bro, zeek, pattern-in-file, pattern-in-traffic, pattern-in-memory, yara, stix2-pattern, sigma, gene, mime-type, identity-card-number, cookie, vulnerability, attachment, malware-sample, link, comment, text, hex, other, named pipe, mutex, target-user, target-email, target-machine, target-org, target-location, target-external, btc, xmr, iban, bic, bank-account-nr, aba-rtn, bin, cc-number, prtn, phone-number, threat-actor, campaign-name, campaign-id, malware-type, uri, authentihash, ssdeep, imphash, pehash, impfuzzy, sha224, sha384, sha512, sha512/224, sha512/256, tlsh, cdhash, filename|authentihash, filename|ssdeep, filename|imphash, filename|impfuzzy, filename|pehash, filename|sha224, filename|sha384, filename|sha512, filename|sha512/224, filename|sha512/256, filename|tlsh, windows-scheduled-task, windows-service-name, windows-service-displayname, whois-registrant-email, whois-registrant-phone, whois-registrant-name, whois-registrant-org, whois-registrar, whois-creation-date, x509-fingerprint-sha1, x509-fingerprint-md5, x509-fingerprint-sha256, dns-soa-email, size-in-bytes, counter, datetime, cpe, port, ip-dst|port, ip-src|port, hostname|port, mac-address, mac-eui-64, email-dst-display-name, email-src-display-name, email-header, email-reply-to, email-x-mailer, email-mime-boundary, email-thread-index, email-message-id, github-username, github-repository, github-organisation, jabber-id, twitter-id, first-name, middle-name, last-name, date-of-birth, place-of-birth, gender, passport-number, passport-country, passport-expiration, redress-number, nationality, visa-number, issue-date-of-the-visa, primary-residence, country-of-residence, special-service-request, frequent-flyer-number, travel-details, payment-details, place-port-of-original-embarkation, place-port-of-clearance, place-port-of-onward-foreign-destination, passenger-name-record-locator-number, mobile-application-id, cortex, boolean, anonymised
```

**Comment by StefanKelm** [comment]
> No worries, thanks for your help. PyMISP was indeed not on the most current version (at least from within `venv`, since we followed a manual which didn't mention to perform updates inside `venv` as well... ;) ). 

Just for the record: PyMISP was not being updated on our instance because we're following the "Point release updates" process described in `docs/UPDATE.md`. Shouldn't PyMISP be mentioned there as well? I know it says the "documentation may not always be up-to-date"...

**Comment by StefanKelm** [comment]
We've resolved this issue.
The problem was that the `REQUIREMENTS` file pointed to an outdated PyMISP commit (cf. https://github.com/MISP/misp-modules/commit/500d4c14c06f5eff7efbde0a666adb8db8d083ca). Shouldn't there be a process for having the `REQUIREMENTS` file updated automagically?
