### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by smclinden** [MISP/misp-modules#385]
v2.4.123 (55bcc4fa470af0bd24db0128e3b2cf3919af1c7e) 
Ubuntu 18.04 installed using the INSTALL script with the -A option.

When trying to test MISP Modules using CURL as described in this document:

https://www.misp-project.org/misp-training/3.1-misp-modules.pdf

I get the following for ALL modules:

 ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
 File "/var/www/MISP/venv/lib/python3.6/site-packages/misp_modules/__init__.py", line 196, in post
 dict_payload = json.loads(jsonpayload)
File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
 return _default_decoder.decode(s)
File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Suggestions would be appreciated.

**Comment by smclinden** [comment]
Found the issue. Whatever formatted the text input to the PDF in the training module compressed two hyphens ('-') into one. So what should have been '--data' was, instead '-data'.
