### ISSUE TITLE
Installing fails w/ socketIO error

### ISSUE THREAD

**Issue by jmgnc** [MISP/misp-modules#387]
When attempting to install the requirements for misp-modules for commit: 824c0031b3aa867284a00ecf60ad992e86d6b5ef

I get the following error with python2:
```
root@ubuntu-bionic:/usr/local/src/misp-modules# pip install -I -r REQUIREMENTS
[...]
Collecting socketio-client==0.5.6 (from -r REQUIREMENTS (line 90))
  Downloading https://files.pythonhosted.org/packages/6e/26/a9483358b9f266a21ae9bfe9012f168c58c1ba34f99dfab26e681bcc061e/socketIO-client-0.5.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nqlbfmt8/socketio-client/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5786: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nqlbfmt8/socketio-client/
```

and the following error with python3:
```
root@ubuntu-bionic:/usr/local/src/misp-modules# pip3 install -I -r REQUIREMENTS
[...]
Collecting socketio-client==0.5.6 (from -r REQUIREMENTS (line 90))
  Downloading https://files.pythonhosted.org/packages/6e/26/a9483358b9f266a21ae9bfe9012f168c58c1ba34f99dfab26e681bcc061e/socketIO-client-0.5.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uw9km44b/socketio-client/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5786: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uw9km44b/socketio-client/
```

The same error happens from a clean virtualenv.

This is from a clean machine, a derivative of misp-vagrant that I'm trying to get working again, but running into tons of errors like the above.

**Comment by Rafiot** [comment]
That's most probably because your locale is set to `C `. If you change it to UTF-8, it should work.

**Comment by jmgnc** [comment]
I had to set it to C.UTF-8 for it to work as UTF-8 is not a valid locale.

```
export LC_ALL=C.UTF-8
```

Please add a check for issues like this, or maybe just hard code the locale in the install.  I shouldn't have to do this much work to install software.

**Comment by jmgnc** [comment]
I closed it because it's fixed for me, but I still think this should be fixed in the general case.
