### ISSUE TITLE
Unable to install modules after upgrade Ubuntu (18 -> 20) and python (3.6 -> 3.8)

### ISSUE THREAD

**Issue by lepaapel** [MISP/misp-modules#401]
Currently installed version… v2.4.125

sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U .
Traceback (most recent call last):
  File "/var/www/MISP/venv/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
    from pip._internal.models.target_python import TargetPython
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/models/target_python.py", line 3, in <module>
    from pip._internal.pep425tags import get_supported, version_info_to_nodot
  File "/var/www/MISP/venv/lib/python3.8/site-packages/pip/_internal/pep425tags.py", line 7, in <module>
    from pip._vendor.packaging.tags import (
ModuleNotFoundError: No module named 'pip._vendor.packaging.tags'

**Comment by Rafiot** [comment]
That's a pip issue, if you google the error message, you will find solutions. As it depends on how pip was installed initially, the solution varies.

**Comment by lepaapel** [comment]
Yes, this is something wrong with pip

According to [this article](https://github.com/pypa/pip/issues/6898) downloading get-pip.py and starting it as www-data was help me:
sudo -u www-data /var/www/MISP/venv/bin/python ./get-pip.py
