### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by alexdjpre** [MISP/misp-modules#413]
Hi, i've installed MISP on a kubernetes cluster but when i try to start mis_modules i receive this error:

2020-07-07 07:03:36,298 - misp-modules - INFO - Launch MISP modules server from current directory.
INFO:misp-modules:Launch MISP modules server from current directory.
Traceback (most recent call last):
File "/usr/local/bin/misp-modules", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.7/site-packages/misp_modules/init.py", line 261, in main
mhandlers, loaded_modules = _launch_from_current_dir()
File "/usr/local/lib/python3.7/site-packages/misp_modules/init.py", line 218, in _launch_from_current_dir
load_helpers(helpersdir=helpersdir)
File "/usr/local/lib/python3.7/site-packages/misp_modules/init.py", line 88, in load_helpers
hhandlers[helpername] = importlib.import_module(helpername)
File "/usr/local/lib/python3.7/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "helpers/cache.py", line 27, in
port = int(os.getenv("REDIS_PORT")) if os.getenv("REDIS_PORT") else 6379
ValueError: invalid literal for int() with base 10: 'tcp://10.100.216.61:6379'

I found a workaround to solve this issue with the missconfiguration of the IP resolution of redis instances. I've forced the redis instances to be on localhost.

The cache.py is:
import os

import redis
import hashlib

port = int(os.getenv("REDIS_PORT")) if os.getenv("REDIS_PORT") else 6379
hostname = os.getenv("REDIS_BACKEND") or '127.0.0.1'
db = int(os.getenv("REDIS_DATABASE")) if os.getenv("REDIS_DATABASE") else 0

Into the REDIS_BACKEND environment i put this entry:
REDIS_BACKEND=redis

Can you help me to solve this issue ?

Bye
Alessandro

**Comment by alexdjpre** [comment]
Any idea ?

**Comment by adulau** [comment]
Yes, `REDIS_PORT` should be 6379 and `REDIS_BACKEND` set to 10.100.216.61.
