### ISSUE TITLE
Potential bug in expansion "yara_query"

### ISSUE THREAD

**Issue by adulau** [MISP/misp-modules#442]
```
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/home/circl/.local/lib/python3.8/site-packages/misp_modules/__init__.py", line 201, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/circl/.local/lib/python3.8/site-packages/misp_modules/__init__.py", line 189, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/yara_query.py", line 35, in handler
    condition, required_module = get_hash_condition(attribute_type, value)
  File "modules/expansion/yara_query.py", line 18, in get_hash_condition
    hashvalue = hashvalue.lower()
```

**Comment by tinamina12** [comment]
I am also facing the exact problem.
