### ISSUE TITLE
Install fails on pip REQUIREMENTS step due to opencv-python

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#461]
I am following the instructions to install on RHEL 7.4, checked out tag v2.4.134 then running the pip step. I don't think this missing module is YOUR problem since it's required by the opencv-python package, but would be grateful for any guidance here.

```
../venv/bin/pip install -U -I -r REQUIREMENTS
Obtaining file:///var/www/MISP/misp-modules (from -r REQUIREMENTS (line 2))
Obtaining pybgpranking from git+https://github.com/D4-project/BGP-Ranking.git/@fd9c0e03af9b61d4bf0b67ac73c7208a55178a54#egg=pybgpranking&subdirectory=client (from -r REQUIREMENTS (line 3))

   (..successful installs omitted here..)

Collecting opencv-python==4.4.0.44 (from -r REQUIREMENTS (line 56))
  Downloading https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz (88.9MB)
    100% |████████████████████████████████| 88.9MB 18kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-20oy5xma/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```
This problem is documented in some details here: https://pypi.org/project/opencv-python/

The (closed) issue in opencv-python is here: https://github.com/skvark/opencv-python/issues/387

The main workaround is to use a recent version of pip that knows how to download the appropriate binary, which an old pip cannot do.

One more question - is there any way for misp-modules to treat opencv-python as optional? I guess then some modules might not work.

**Comment by chrisinmtown** [comment]
Please consider mentioning in your install instructions about using a modern version of pip. The old pip that I was using, version 9, does not know how to download the precompiled binaries that opencv-python offers, so attempts to build -- that's all wrong.
