### ISSUE TITLE
Misp-modules fails to start due to missing dependency dnsdb2

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/misp-modules#462]
I'm using the version tagged v2.4.134 on my first attempt at installing and running misp-modules, forgive if this is a dumb question.  When I try to start, misp-modules fails with the following message.  Is the dnsdb2 package just missing from the REQUIREMENTS file? 
```
$ /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s
No module named 'dnsdb2'
2020-12-09 22:38:28,292 - misp-modules - INFO - Launch MISP modules server from package.
2020-12-09 22:38:28,293 - misp-modules - INFO - Helper loaded cache
2020-12-09 22:38:28,293 - misp-modules - INFO - Unable to load MISP modules from package.
```
Next step, try to install that module; but not much better luck:
```
(venv) bash-4.2$ pip3 install dnsdb2
Collecting dnsdb2
  Using cached dnsdb2-1.1.1.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: requests in ./venv/lib/python3.6/site-packages (from dnsdb2) (2.24.0)
Collecting importlib
  Using cached importlib-1.0.4.zip (7.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wfqbfdsy/importlib_0205792223aa4e218ec50f87de2023b8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wfqbfdsy/importlib_0205792223aa4e218ec50f87de2023b8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p0i25s4t
         cwd: /tmp/pip-install-wfqbfdsy/importlib_0205792223aa4e218ec50f87de2023b8/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/www/MISP/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        import distutils.core
      File "/var/www/MISP/venv/lib64/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/var/www/MISP/venv/lib64/python3.6/imp.py", line 19, in <module>
        from importlib._bootstrap import _ERR_MSG, _exec, _load, _builtin_from_name
    ModuleNotFoundError: No module named 'importlib._bootstrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I think I saw an issue about importlib, gonna go check that next.

**Comment by chrisinmtown** [comment]
I see I created a dupe of https://github.com/MISP/misp-modules/issues/449

But still, please document the need for dnsdb2

**Comment by chrisinmtown** [comment]
Duplicate.
