### ISSUE TITLE
Nosetest fails on the btc_steroids.py module

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/misp-modules#492]
```
$ nosetests --with-coverage --cover-package=misp_modules
..SSSSSSSSSSSSSSSSS......2021-05-02 22:31:21,382 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
  File "/home/travis/build/MISP/misp-modules/misp_modules/__init__.py", line 200, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(dict_payload['module'], jsonpayload))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/python/3.6.7/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/travis/build/MISP/misp-modules/misp_modules/__init__.py", line 188, in run_request
    response = mhandlers[module].handler(q=jsonpayload)
  File "/home/travis/build/MISP/misp-modules/misp_modules/modules/expansion/btc_steroids.py", line 160, in handler
    jreq = req.json()
...
```

**Comment by ostefano** [comment]
This is now fixed.
