### ISSUE TITLE
virustotal  KeyError: 'submission_names

### ISSUE THREAD

**Issue by giedriusramas** [MISP/misp-modules#50]
I get following error when trying to test virustotal module.

2016-09-08 14:01:50,272 - misp-modules - ERROR - Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/**init**.py", line 195, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 183, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 39, in handler
    r["results"] += getDomain(q["domain"], key)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 85, in getDomain
    toReturn += getIP(res["ip_address"], key, True)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 67, in getIP
    toReturn += getMoreInfo(req, key)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 141, in getMoreInfo
    "values":data["submission_names"],
KeyError: 'submission_names'
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/**init**.py", line 195, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 183, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 39, in handler
    r["results"] += getDomain(q["domain"], key)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 85, in getDomain
    toReturn += getIP(res["ip_address"], key, True)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 67, in getIP
    toReturn += getMoreInfo(req, key)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/virustotal.py", line 141, in getMoreInfo
    "values":data["submission_names"],
KeyError: 'submission_names'
{"error": "Something went wrong, look in the server logs for details"}[14:01:50]

To test module I run following command. curl -s http://127.0.0.1:6666/query -H "Content-Type: application/json" --data @body_virustotal.json -X POST

body_virustotal.json

{
  "domain": "aijazeera.org",
  "module": "virustotal",
  "config":
{
"apikey": "myAPIkey", 
"event_limit": "5"
}
}

**Comment by CheYenBzh** [comment]
hi,

You posted is old, but I got this error too, you can delete it by adding a test on this key. I'll submit PR, this may be useful for others users.

Replace:
```
r.append({"types":["malware-sample"], 
                "categories":["Payload delivery"],
                "values":data["submission_names"],
                "data": str(base64.b64encode(malsample), 'utf-8')
                }
              ) 
```

by:
```
if isset(data, "submission_names"):
    r.append({"types":["malware-sample"], 
                "categories":["Payload delivery"],
                "data": str(base64.b64encode(malsample), 'utf-8')
                }
              ) 
else:
    r.append({"types":["malware-sample"], 
                "categories":["Payload delivery"],
                "values":data["submission_names"],
                "data": str(base64.b64encode(malsample), 'utf-8')
                }
              ) 
```
in the file virustotal.py

CheYen
