### ISSUE TITLE
HTTP error authentication incorrect?

### ISSUE THREAD

**Issue by xme** [MISP/misp-modules#51]
I just upgraded my MISP docker with the latest git version of misp-modules.
It reports the following exception:

ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/**init**.py", line 195, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/__init__.py", line 183, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/local/lib/python3.4/dist-packages/misp_modules/modules/expansion/circl_passivedns.py", line 32, in handler
    res = x.query(toquery)
  File "/usr/local/lib/python3.4/dist-packages/pypdns/api.py", line 47, in query
    raise Exception('HTTP error authentication incorrect?')
Exception: HTTP error authentication incorrect?

Any idea?
Some passivedns lookups are ok, others aren't?

/x

**Comment by Rafiot** [comment]
This is weird. Are you sure the login/password is correct? Can you try to connect to pdns in your browser?

**Comment by Rafiot** [comment]
@xme did you find a solution?
