### ISSUE TITLE
Installation of misp-modules requirements are failing

### ISSUE THREAD

**Issue by shinobu55** [MISP/misp-modules#563]
Hello,

when I am trying to install the dependencies for misp-modules, I am receiving an error on the installation of trustar.

Collecting trustar from git+https://github.com/SteveClement/trustar-python.git@6954eae38e0c77eaeef26084b6c5fd033925c1c7#egg=trustar (from -r REQUIREMENTS (line 59))
  Cloning https://github.com/SteveClement/trustar-python.git (to 6954eae38e0c77eaeef26084b6c5fd033925c1c7) to /tmp/pip-build-4esxnzn6/trustar
  Could not find a tag or branch '6954eae38e0c77eaeef26084b6c5fd033925c1c7', assuming commit.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/var/www/MISP/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2299, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'invalid_unless_false'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4esxnzn6/trustar/setup.py", line 33, in <module>
        use_2to3=False
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/var/www/MISP/venv/lib64/python3.6/site-packages/setuptools/dist.py", line 318, in __init__
        _Distribution.__init__(self, attrs)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/var/www/MISP/venv/lib64/python3.6/site-packages/setuptools/dist.py", line 376, in finalize_options
        ep.load()(self, ep.name, value)
      File "/var/www/MISP/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
        return self.resolve()
      File "/var/www/MISP/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2301, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'invalid_unless_false'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4esxnzn6/trustar/

Since our envrionment has no available ubuntu images, I am running misp on a centos7 machine.

Any ideas or solutions how to solve this? Thanks in advance!

**Comment by shinobu55** [comment]
Apologies it seems like there was an issue before for that and the search initally did not pick it up. https://github.com/MISP/misp-modules/issues/523

**Comment by adulau** [comment]
Thanks for the feedback.
