### ISSUE TITLE
Fail to start Modules on ARM server

### ISSUE THREAD

**Issue by EHermanOliv** [MISP/misp-modules#569]
Hello all, 

I instaled a new server 2 months ago in a Raspberry Pi 4 and it have been running prety smoth, but the MISP-modules start is failing. 
The server use to run on a X64 Ubuntu Server virtual machine and the modules installation there was succesfull, so I repeted the same process in the Raspberry Pi server but it fails. 

I suspect that the issue is related to an library as I saw that some libraries names have the ARM next to them and this may cause issues. However, I was not able to identify it as the error and how it is handle by (/var/www/MISP/venv/lib/python3.9/site-packages/pymisp/tools/__init__.py) looks to just give a generic output error. 

Below is my server config and the errors that I get. 

Currently installed version… v2.4.158 (78e760f831a4c50677533029e59abdf9cd505203)
PHP 7.4 
(MISP is running well, issue just with the modules)
```
 $ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Command error

```
sudo /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s &
[1] 12701
uwhois module not installed.
/var/www/MISP/venv/lib/python3.9/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
ERROR: Unable to import URLObject, pyfaup missing
Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.9/site-packages/misp_modules/modules/import_mod/email_import.py", line 11, in <module>
    from pymisp.tools import URLObject
ImportError: cannot import name 'URLObject' from 'pymisp.tools' (/var/www/MISP/venv/lib/python3.9/site-packages/pymisp/tools/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/venv/lib/python3.9/site-packages/misp_modules/__init__.py", line 41, in <module>
    from .modules import *  # noqa
  File "/var/www/MISP/venv/lib/python3.9/site-packages/misp_modules/modules/__init__.py", line 2, in <module>
    from .import_mod import *  # noqa
  File "/var/www/MISP/venv/lib/python3.9/site-packages/misp_modules/modules/import_mod/email_import.py", line 13, in <module>
    raise ImportError('Unable to import URLObject, pyfaup missing')
ImportError: Unable to import URLObject, pyfaup missing
2022-05-10 09:20:57,870 - misp-modules - INFO - Launch MISP modules server from package.
INFO: Launch MISP modules server from package.
2022-05-10 09:20:57,874 - misp-modules - INFO - Helper loaded cache
INFO: Helper loaded cache
2022-05-10 09:20:57,874 - misp-modules - INFO - Unable to load MISP modules from package.
INFO: Unable to load MISP modules from package.
^C
[1]+  Done                    sudo /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s

```
When I restart the process I got this output

```
sudo systemctl status misp-modules
● misp-modules.service - System-wide instance of the MISP Modules
     Loaded: loaded (/etc/systemd/system/misp-modules.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2022-05-10 09:22:39 EDT; 2min 54s ago
    Process: 12719 ExecStart=/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s (code=exited, status=0/SUCCESS)
   Main PID: 12719 (code=exited, status=0/SUCCESS)
        CPU: 5.373s

May 10 09:22:38 raspberrypiserver misp-modules[12719]: ImportError: Unable to import URLObject, pyfaup missing
May 10 09:22:38 raspberrypiserver misp-modules[12719]: uwhois module not installed.
May 10 09:22:38 raspberrypiserver misp-modules[12719]: 2022-05-10 09:22:38,706 - misp-modules - INFO - Launch MISP modules server from package.
May 10 09:22:38 raspberrypiserver misp-modules[12719]: INFO: Launch MISP modules server from package.
May 10 09:22:38 raspberrypiserver misp-modules[12719]: 2022-05-10 09:22:38,710 - misp-modules - INFO - Helper loaded cache
May 10 09:22:38 raspberrypiserver misp-modules[12719]: INFO: Helper loaded cache
May 10 09:22:38 raspberrypiserver misp-modules[12719]: 2022-05-10 09:22:38,710 - misp-modules - INFO - Unable to load MISP modules from package.
May 10 09:22:38 raspberrypiserver misp-modules[12719]: INFO: Unable to load MISP modules from package.
May 10 09:22:39 raspberrypiserver systemd[1]: misp-modules.service: Succeeded.
May 10 09:22:39 raspberrypiserver systemd[1]: misp-modules.service: Consumed 5.373s CPU time.
```

Some extra information
```
/usr/local/src/misp-modules# pip list | grep pyfaup
pyfaup                 1.2
```

```
pip install -U git+https://github.com/Lookyloo/uwhoisd.git
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/Lookyloo/uwhoisd.git
  Cloning https://github.com/Lookyloo/uwhoisd.git to /tmp/pip-req-build-2ps7xc_h
  Running command git clone -q https://github.com/Lookyloo/uwhoisd.git /tmp/pip-req-build-2ps7xc_h
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: tornado<7.0,>=6.1 in ./venv/lib/python3.9/site-packages (from uwhoisd==0.1.0) (6.1)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.3 in ./venv/lib/python3.9/site-packages (from uwhoisd==0.1.0) (4.10.0)
Collecting redis<4.0.0,>=3.5.3
  Downloading https://www.piwheels.org/simple/redis/redis-3.5.3-py2.py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 389 kB/s
Collecting publicsuffix2<3.0,>=2.20191221
  Downloading https://www.piwheels.org/simple/publicsuffix2/publicsuffix2-2.20191221-py2.py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 702 kB/s
Requirement already satisfied: soupsieve>1.2 in ./venv/lib/python3.9/site-packages (from beautifulsoup4<5.0.0,>=4.9.3->uwhoisd==0.1.0
Building wheels for collected packages: uwhoisd
  Building wheel for uwhoisd (PEP 517) ... done
  Created wheel for uwhoisd: filename=uwhoisd-0.1.0-py3-none-any.whl size=10473 sha256=5d0880167050b18a665694b31ef1e5550d59ba80ff26b9
  Stored in directory: /tmp/pip-ephem-wheel-cache-rppdv4iy/wheels/10/cd/98/545024b5209fc6fcf732cb2fe8ba6f2934a537778da45ffe80
Successfully built uwhoisd
Installing collected packages: redis, publicsuffix2, uwhoisd
  Attempting uninstall: redis
    Found existing installation: redis 4.1.4
    Uninstalling redis-4.1.4:
      Successfully uninstalled redis-4.1.4
Successfully installed publicsuffix2-2.20191221 redis-3.5.3 uwhoisd-0.1.0
```
```

pip install -I --upgrade -r REQUIREMENTS
Processing /usr/local/src/misp-modules
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Ignoring asynctest: markers 'python_version < "3.8"' don't match your environment
Ignoring backports.zoneinfo: markers 'python_version < "3.9"' don't match your environment
Collecting pybgpranking
  Using cached pybgpranking-0.1-py3-none-any.whl
Collecting pyipasnhistory
  Using cached pyipasnhistory-0.1-py3-none-any.whl
Collecting pyintel471
  Using cached pyintel471-0.1-py3-none-any.whl
Collecting trustar
  Using cached trustar-0.3.34-py3-none-any.whl
Collecting odtreader
  Using cached ODTReader-0.0.3-py3-none-any.whl
Collecting pydnstrails
  Using cached pydnstrails-1.0-py3-none-any.whl
Collecting pyonyphe
  Using cached pyonyphe-2.0-py3-none-any.whl
Ignoring idna-ssl: markers 'python_version < "3.7"' don't match your environment
Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
Ignoring importlib-resources: markers 'python_version < "3.9"' don't match your environment
Ignoring numpy: markers 'python_version < "3.10" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your
Ignoring typing-extensions: markers 'python_version < "3.8"' don't match your environment
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.2 MB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4_python3_runtime-4.8-py3-none-any.whl
Collecting apiosintds==1.8.3
  Using cached apiosintDS-1.8.3-py3-none-any.whl (13 kB)
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting argparse==1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting assemblyline-client==4.2.2
  Using cached assemblyline_client-4.2.2-py2.py3-none-any.whl (52 kB)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting backoff==1.11.1
  Using cached backoff-1.11.1-py2.py3-none-any.whl (13 kB)
Collecting backscatter==0.2.4
  Using cached backscatter-0.2.4-py3-none-any.whl (11 kB)
Collecting beautifulsoup4==4.10.0
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting bidict==0.21.4
  Using cached bidict-0.21.4-py3-none-any.whl (36 kB)
Collecting blockchain==1.4.4
  Using cached blockchain-1.4.4-py3-none-any.whl
Collecting censys==2.1.2
  Using cached censys-2.1.2-py3-none-any.whl (53 kB)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (447 kB)
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting charset-normalizer==2.0.12
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting clamd==1.0.2
  Using cached clamd-1.0.2-py2.py3-none-any.whl (6.7 kB)
Collecting click-plugins==1.1.1
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting click==8.0.4
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting colorclass==2.2.2
  Using cached colorclass-2.2.2-py2.py3-none-any.whl (18 kB)
Collecting commonmark==0.9.1
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting compressed-rtf==1.0.6
  Using cached compressed_rtf-1.0.6-py3-none-any.whl
Collecting configparser==5.2.0
  Using cached configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting crowdstrike-falconpy==1.0.5
  Using cached crowdstrike_falconpy-1.0.5-py3-none-any.whl (359 kB)
Collecting cryptography==36.0.1
  Using cached cryptography-36.0.1-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (3.3 MB)
Collecting decorator==5.1.1
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting deprecated==1.2.13
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting dnsdb2==1.1.4
  Using cached dnsdb2-1.1.4-py3-none-any.whl
Collecting dnspython==2.2.0
  Using cached dnspython-2.2.0-py3-none-any.whl (266 kB)
Collecting domaintools-api==0.6.1
  Using cached domaintools_api-0.6.1-py2.py3-none-any.whl (18 kB)
Collecting easygui==0.98.2
  Using cached easygui-0.98.2-py2.py3-none-any.whl (92 kB)
Collecting ebcdic==1.1.1
  Using cached ebcdic-1.1.1-py2.py3-none-any.whl (128 kB)
Collecting enum-compat==0.0.3
  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Collecting extract-msg==0.30.8
  Using cached extract_msg-0.30.8-py2.py3-none-any.whl (82 kB)
Collecting ezodf==0.3.2
  Using cached ezodf-0.3.2-py2.py3-none-any.whl
Collecting filelock==3.6.0
  Using cached filelock-3.6.0-py3-none-any.whl (10.0 kB)
Collecting frozenlist==1.3.0
  Using cached frozenlist-1.3.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (156 kB)
Collecting future==0.18.2
  Using cached future-0.18.2-py3-none-any.whl
Collecting geoip2==4.5.0
  Using cached geoip2-4.5.0-py2.py3-none-any.whl (26 kB)
Collecting httplib2==0.20.4
  Using cached httplib2-0.20.4-py3-none-any.whl (96 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting imapclient==2.2.0
  Using cached IMAPClient-2.2.0-py2.py3-none-any.whl (179 kB)
Collecting isodate==0.6.1
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Collecting itsdangerous==2.1.0
  Using cached itsdangerous-2.1.0-py3-none-any.whl (15 kB)
Collecting jbxapi==3.17.2
  Using cached jbxapi-3.17.2-py2.py3-none-any.whl (17 kB)
Collecting jeepney==0.7.1
  Using cached jeepney-0.7.1-py3-none-any.whl (54 kB)
Collecting json-log-formatter==0.5.1
  Using cached JSON_log_formatter-0.5.1-py3-none-any.whl
Collecting jsonschema==4.4.0
  Using cached jsonschema-4.4.0-py3-none-any.whl (72 kB)
Collecting keyring==23.5.0
  Using cached keyring-23.5.0-py3-none-any.whl (33 kB)
Collecting lark-parser==0.12.0
  Using cached lark_parser-0.12.0-py2.py3-none-any.whl (103 kB)
Collecting lief==0.11.5
  Using cached lief-0.11.5-cp39-cp39-manylinux2014_aarch64.whl (3.2 MB)
Collecting lxml==4.8.0
  Using cached lxml-4.8.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (6.6 MB)
Collecting maclookup==1.0.3
  Using cached maclookup-1.0.3-py2.py3-none-any.whl (10 kB)
Collecting markdownify==0.5.3
  Using cached markdownify-0.5.3-py3-none-any.whl (8.0 kB)
Collecting maxminddb==2.2.0
  Using cached maxminddb-2.2.0-py2.py3-none-any.whl
Collecting more-itertools==8.12.0
  Using cached more_itertools-8.12.0-py3-none-any.whl (54 kB)
Collecting msoffcrypto-tool==5.0.0
  Using cached msoffcrypto_tool-5.0.0-py3-none-any.whl (33 kB)
Collecting multidict==6.0.2
  Using cached multidict-6.0.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (116 kB)
Collecting mwdblib==4.1.0
  Using cached mwdblib-4.1.0-py3-none-any.whl (42 kB)
Collecting ndjson==0.3.1
  Using cached ndjson-0.3.1-py2.py3-none-any.whl (5.3 kB)
Collecting np==1.0.2
  Using cached np-1.0.2-py3-none-any.whl
Collecting oauth2==1.9.0.post1
  Using cached oauth2-1.9.0.post1-py2.py3-none-any.whl (25 kB)
Collecting olefile==0.46
  Using cached olefile-0.46-py2.py3-none-any.whl
Collecting oletools==0.60
  Using cached oletools-0.60-py2.py3-none-any.whl (968 kB)
Collecting opencv-python==4.5.5.62
  Using cached opencv_python-4.5.5.62-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (39.0 MB)
Collecting packaging==21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pandas-ods-reader==0.1.2
  Using cached pandas_ods_reader-0.1.2-py3-none-any.whl (7.6 kB)
Collecting pandas==1.3.5
  Using cached pandas-1.3.5-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (10.9 MB)
Collecting passivetotal==2.5.8
  Using cached passivetotal-2.5.8-py3-none-any.whl (112 kB)
Collecting pcodedmp==1.2.6
  Using cached pcodedmp-1.2.6-py2.py3-none-any.whl (30 kB)
Collecting pdftotext==2.2.2
  Using cached pdftotext-2.2.2-cp39-cp39-linux_aarch64.whl
Collecting pillow==9.0.1
  Using cached Pillow-9.0.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.2 MB)
Collecting progressbar2==4.0.0
  Using cached progressbar2-4.0.0-py2.py3-none-any.whl (26 kB)
Collecting psutil==5.9.0
  Using cached psutil-5.9.0-cp39-cp39-linux_aarch64.whl
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pycryptodome==3.14.1
  Using cached pycryptodome-3.14.1-cp35-abi3-manylinux2014_aarch64.whl (1.5 MB)
Collecting pycryptodomex==3.14.1
  Using cached pycryptodomex-3.14.1-cp35-abi3-linux_aarch64.whl
Collecting pydeep2==0.5.1
  Using cached pydeep2-0.5.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (24 kB)
Collecting pyeupi==1.1
  Using cached pyeupi-1.1-py3-none-any.whl (6.0 kB)
Collecting pyfaup==1.2
  Using cached pyfaup-1.2-py2.py3-none-any.whl (331 kB)
Collecting pygeoip==0.3.2
  Using cached pygeoip-0.3.2-py2.py3-none-any.whl (20 kB)
Collecting pygments==2.11.2
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting pymisp[email,fileobjects,openioc,pdfexport,url]==2.4.155.1
  Using cached pymisp-2.4.155.1-py3-none-any.whl (502 kB)
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pypdns==1.5.2
  Using cached pypdns-1.5.2-py3-none-any.whl (4.5 kB)
Collecting pypssl==2.2
  Using cached pypssl-2.2-py3-none-any.whl (3.7 kB)
Collecting pyrsistent==0.18.1
  Using cached pyrsistent-0.18.1-cp39-cp39-linux_aarch64.whl
Collecting pytesseract==0.3.9
  Using cached pytesseract-0.3.9-py2.py3-none-any.whl (14 kB)
Collecting python-baseconv==1.2.2
  Using cached python_baseconv-1.2.2-py3-none-any.whl
Collecting python-dateutil==2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting python-docx==0.8.11
  Using cached python_docx-0.8.11-py3-none-any.whl
Collecting python-engineio==4.3.1
  Using cached python_engineio-4.3.1-py3-none-any.whl (52 kB)
Collecting python-magic==0.4.25
  Using cached python_magic-0.4.25-py2.py3-none-any.whl (13 kB)
Collecting python-pptx==0.6.21
  Using cached python_pptx-0.6.21-py3-none-any.whl
Collecting python-socketio[client]==5.5.2
  Using cached python_socketio-5.5.2-py3-none-any.whl (56 kB)
Collecting python-utils==3.1.0
  Using cached python_utils-3.1.0-py2.py3-none-any.whl (19 kB)
Collecting pytz-deprecation-shim==0.1.0.post0
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting pytz==2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (731 kB)
Collecting pyzbar==0.1.8
  Using cached pyzbar-0.1.8-py2.py3-none-any.whl (28 kB)
Collecting pyzipper==0.3.5
  Using cached pyzipper-0.3.5-py2.py3-none-any.whl (162 kB)
Collecting rdflib==6.1.1
  Using cached rdflib-6.1.1-py3-none-any.whl (482 kB)
Collecting redis==3.5.3
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 244 kB/s
Collecting reportlab==3.6.8
  Using cached reportlab-3.6.8-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.7 MB)
Collecting requests-cache==0.6.4
  Using cached requests_cache-0.6.4-py2.py3-none-any.whl (28 kB)
Collecting requests-file==1.5.1
  Using cached requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting rich==11.2.0
  Using cached rich-11.2.0-py3-none-any.whl (217 kB)
Collecting rtfde==0.0.2
  Using cached RTFDE-0.0.2-py3-none-any.whl (34 kB)
Collecting secretstorage==3.3.1
  Using cached SecretStorage-3.3.1-py3-none-any.whl (15 kB)
Collecting setuptools==60.9.3
  Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
Collecting shodan==1.27.0
  Using cached shodan-1.27.0-py3-none-any.whl
Collecting sigmatools==0.19.1
  Using cached sigmatools-0.19.1-py3-none-any.whl (214 kB)
Collecting simplejson==3.17.6
  Using cached simplejson-3.17.6-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (130 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting socialscan==1.4.2
  Using cached socialscan-1.4.2-py3-none-any.whl (21 kB)
Collecting socketio-client==0.5.7.4
  Using cached socketIO_client-0.5.7.4-py3-none-any.whl
Collecting soupsieve==2.3.1
  Using cached soupsieve-2.3.1-py3-none-any.whl (37 kB)
Collecting sparqlwrapper==1.8.5
  Using cached SPARQLWrapper-1.8.5-py3-none-any.whl (26 kB)
Collecting stix2-patterns==1.3.2
  Using cached stix2_patterns-1.3.2-py2.py3-none-any.whl (65 kB)
Collecting stix2==3.0.1
  Using cached stix2-3.0.1-py2.py3-none-any.whl (177 kB)
Collecting tabulate==0.8.9
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting tau-clients==0.2.1
  Using cached tau_clients-0.2.1-py3-none-any.whl (29 kB)
Collecting taxii2-client==2.3.0
  Using cached taxii2_client-2.3.0-py2.py3-none-any.whl (24 kB)
Collecting tldextract==3.2.0
  Using cached tldextract-3.2.0-py3-none-any.whl (87 kB)
Collecting tornado==6.1
  Using cached tornado-6.1-cp39-cp39-manylinux2014_aarch64.whl (427 kB)
Collecting tqdm==4.63.0
  Using cached tqdm-4.63.0-py2.py3-none-any.whl (76 kB)
Collecting tzdata==2021.5
  Using cached tzdata-2021.5-py2.py3-none-any.whl (339 kB)
Collecting tzlocal==4.1
  Using cached tzlocal-4.1-py3-none-any.whl (19 kB)
Collecting unicodecsv==0.14.1
  Using cached unicodecsv-0.14.1-py3-none-any.whl
Collecting url-normalize==1.4.3
  Using cached url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Collecting urlarchiver==0.2
  Using cached urlarchiver-0.2-py3-none-any.whl
Collecting urllib3==1.26.8
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting validators==0.14.0
  Using cached validators-0.14.0-py3-none-any.whl
Collecting vt-graph-api==1.1.3
  Using cached vt_graph_api-1.1.3-py3-none-any.whl (37 kB)
Collecting vt-py==0.13.1
  Using cached vt_py-0.13.1-py3-none-any.whl (17 kB)
Collecting vulners==2.0.2
  Using cached vulners-2.0.2-py3-none-any.whl (27 kB)
Collecting wand==0.6.7
  Using cached Wand-0.6.7-py2.py3-none-any.whl (139 kB)
Collecting websocket-client==1.3.1
  Using cached websocket_client-1.3.1-py3-none-any.whl (54 kB)
Collecting wrapt==1.13.3
  Using cached wrapt-1.13.3-cp39-cp39-linux_aarch64.whl
Collecting xlrd==2.0.1
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Collecting xlsxwriter==3.0.3
  Using cached XlsxWriter-3.0.3-py3-none-any.whl (149 kB)
Collecting yara-python==3.8.1
  Using cached yara_python-3.8.1-cp39-cp39-linux_aarch64.whl
Collecting yarl==1.7.2
  Using cached yarl-1.7.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (321 kB)
Collecting zipp==3.7.0
  Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting importlib-metadata>=3.6
  Using cached importlib_metadata-4.11.2-py3-none-any.whl (17 kB)
Collecting numpy>=1.17.3
  Using cached numpy-1.22.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.4 MB)
Building wheels for collected packages: misp-modules
  Building wheel for misp-modules (PEP 517) ... done
  Created wheel for misp-modules: filename=misp_modules-1.0-py3-none-any.whl size=315921 sha256=3fdc48e311e42c798f3101e3f1faba7209b85
  Stored in directory: /root/.cache/pip/wheels/25/fc/50/ea5558b86fe7d36122c6fb8f48d087de89e0742202ea7f1579
Successfully built misp-modules
Installing collected packages: pycparser, cffi, olefile, cryptography, urllib3, tzdata, pyparsing, pcodedmp, multidict, msoffcrypto-tss, charset-normalizer, certifi, zipp, yarl, wrapt, soupsieve, six, requests, pytz-deprecation-shim, python-engineio, pyrsistent, olers, async-timeout, aiosignal, websocket-client, url-normalize, tzlocal, setuptools, secretstorage, rtfde, requests-file, pytz, python, pygments, pycryptodomex, pillow, numpy, jsonschema, itsdangerous, isodate, importlib-metadata, imapclient, filelock, ebcdic, deprecark, colorama, click, beautifulsoup4, antlr4-python3-runtime, aiohttp, xlsxwriter, vt-py, validators, unicodecsv, tqdm, tornado, tldeio-client, simplejson, rich, requests-cache, reportlab, redis, rdflib, pyzipper, pyyaml, python-magic, python-baseconv, pymisp, pyfaussbar2, pandas, packaging, more-itertools, maxminddb, lxml, lief, keyring, json-log-formatter, httplib2, future, ezodf, extract-msg, , chardet, backoff, argparse, appdirs, yara-python, xlrd, wand, vulners, vt-graph-api, urlarchiver, trustar, taxii2-client, tau-cliengmatools, shodan, pyzbar, python-pptx, python-docx, pytesseract, pypssl, pypdns, pyonyphe, pyipasnhistory, pyintel471, pygeoip, pyeup passivetotal, pandas-ods-reader, opencv-python, odtreader, oauth2, np, ndjson, mwdblib, misp-modules, markdownify, maclookup, jbxapisdb2, crowdstrike-falconpy, clamd, censys, blockchain, backscatter, assemblyline-client, apiosintds
Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 antlr4-python3-runtime-4.8 apiosintds-1.8.3 appdirs-1.4.4 argparse-1.4.0 assemblttrs-21.4.0 backoff-1.11.1 backscatter-0.2.4 beautifulsoup4-4.10.0 bidict-0.21.4 blockchain-1.4.4 censys-2.1.2 certifi-2021.10.8 cffi-2.0.12 clamd-1.0.2 click-8.0.4 click-plugins-1.1.1 colorama-0.4.4 colorclass-2.2.2 commonmark-0.9.1 compressed-rtf-1.0.6 configparseography-36.0.1 decorator-5.1.1 deprecated-1.2.13 dnsdb2-1.1.4 dnspython-2.2.0 domaintools-api-0.6.1 easygui-0.98.2 ebcdic-1.1.1 enum-3.2 filelock-3.6.0 frozenlist-1.3.0 future-0.18.2 geoip2-4.5.0 httplib2-0.20.4 idna-3.3 imapclient-2.2.0 importlib-metadata-4.11.2 is17.2 jeepney-0.7.1 json-log-formatter-0.5.1 jsonschema-4.4.0 keyring-23.5.0 lark-parser-0.12.0 lief-0.11.5 lxml-4.8.0 maclookup-1.0.3modules-1.0 more-itertools-8.12.0 msoffcrypto-tool-5.0.0 multidict-6.0.2 mwdblib-4.1.0 ndjson-0.3.1 np-1.0.2 numpy-1.22.3 oauth2-1.9.tools-0.60 opencv-python-4.5.5.62 packaging-21.3 pandas-1.3.5 pandas-ods-reader-0.1.2 passivetotal-2.5.8 pcodedmp-1.2.6 pdftotext-2.2l-5.9.0 pybgpranking-0.1 pycparser-2.21 pycryptodome-3.14.1 pycryptodomex-3.14.1 pydeep2-0.5.1 pydnstrails-1.0 pyeupi-1.1 pyfaup-1.2 -0.1 pyipasnhistory-0.1 pymisp-2.4.155.1 pyonyphe-2.0 pyparsing-3.0.7 pypdns-1.5.2 pypssl-2.2 pyrsistent-0.18.1 pytesseract-0.3.9 pyt python-docx-0.8.11 python-engineio-4.3.1 python-magic-0.4.25 python-pptx-0.6.21 python-socketio-5.5.2 python-utils-3.1.0 pytz-2019.3l-6.0 pyzbar-0.1.8 pyzipper-0.3.5 rdflib-6.1.1 redis-4.1.4 reportlab-3.6.8 requests-2.27.1 requests-cache-0.6.4 requests-file-1.5.1 r.1 setuptools-60.9.3 shodan-1.27.0 sigmatools-0.19.1 simplejson-3.17.6 six-1.16.0 socialscan-1.4.2 socketio-client-0.5.7.4 soupsieve-ix2-patterns-1.3.2 tabulate-0.8.9 tau-clients-0.2.1 taxii2-client-2.3.0 tldextract-3.2.0 tornado-6.1 tqdm-4.63.0 trustar-0.3.34 tzdatrl-normalize-1.4.3 urlarchiver-0.2 urllib3-1.26.8 validators-0.14.0 vt-graph-api-1.1.3 vt-py-0.13.1 vulners-2.0.2 wand-0.6.7 websockelsxwriter-3.0.3 yara-python-3.8.1 yarl-1.7.2 zipp-3.7.0
(venv) root@raspberrypiserver:/usr/local/src/misp-modules# /var/www/MISP/venv/bin/pip install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /usr/local/src/misp-modules
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: redis>=3 in /var/www/MISP/venv/lib/python3.9/site-packages (from misp-modules==1.0) (4.1.4)
Requirement already satisfied: tornado in /var/www/MISP/venv/lib/python3.9/site-packages (from misp-modules==1.0) (6.1)
Requirement already satisfied: psutil in /var/www/MISP/venv/lib/python3.9/site-packages (from misp-modules==1.0) (5.9.0)
Requirement already satisfied: deprecated>=1.2.3 in /var/www/MISP/venv/lib/python3.9/site-packages (from redis>=3->misp-modules==1.0) (1.2.13)
Requirement already satisfied: packaging>=20.4 in /var/www/MISP/venv/lib/python3.9/site-packages (from redis>=3->misp-modules==1.0) (21.3)
Requirement already satisfied: wrapt<2,>=1.10 in /var/www/MISP/venv/lib/python3.9/site-packages (from deprecated>=1.2.3->redis>=3->misp-modules==1.0) (1.13.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /var/www/MISP/venv/lib/python3.9/site-packages (from packaging>=20.4->redis>=3->misp-modules==1.0) (3.0.7)
Building wheels for collected packages: misp-modules
  Building wheel for misp-modules (PEP 517) ... done
  Created wheel for misp-modules: filename=misp_modules-1.0-py3-none-any.whl size=315921 sha256=09e460b82c55c77598d94349b7a6eb823a25552485494385ecdb9004b99d09f5
  Stored in directory: /root/.cache/pip/wheels/25/fc/50/ea5558b86fe7d36122c6fb8f48d087de89e0742202ea7f1579
Successfully built misp-modules
Installing collected packages: misp-modules
  Attempting uninstall: misp-modules
    Found existing installation: misp-modules 1.0
    Uninstalling misp-modules-1.0:
      Successfully uninstalled misp-modules-1.0
Successfully installed misp-modules-1.0
```

I'm quite lost with this and looks like everithing is configured correctly, but I'm suspecting that MISP-modules is not compatible with RaspberryPi and ARM architecture, this is the only reason that I could find to it don't work. 
Much appreciated the help and comments. 

Regards,

**Comment by adulau** [comment]
Is it still the case? If so, feel free to reopen the issue.

**Comment by EHermanOliv** [comment]
It can be closed. 
I identified that the reason that I had this issue was because i was using a ARM system and some of the libriaries used in the modules do not have suport to ARM arquitecture systems, so not all of the requirements of the modules libraries can be meet in ARM systems. 
moving my lab to a X64/X86 system it works perfectly.
