### ISSUE TITLE
Email Import Module Error if certain email fields don't exist

### ISSUE THREAD

**Issue by cyber-guy** [MISP/misp-modules#88]
It looks like there may be some missing logic if certain email fields don't exist when trying to import attributes from an email using the email import module. Below is the full error code, but I'm guessing it's due to "In-Reply-To" not existing in the email i was trying to import.

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/misp_modules-1.0-py3.4.egg/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python3.4/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/misp_modules-1.0-py3.4.egg/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "/usr/lib/python3.4/site-packages/misp_modules-1.0-py3.4.egg/misp_modules/modules/import_mod/email_import.py", line 55, in handler
    **results.append({"values": message.get('In-Reply-To').strip(),
AttributeError: 'NoneType' object has no attribute 'strip'**

**Comment by cyber-guy** [comment]
Looking a bit at the source code, TypeError checks for NoneType are probably also needed for X-Mailer and Thread-Index. There may be others, but those also stood out as not being in every email.

**Comment by Rafiot** [comment]
Woops, right, I'll fix it later today

**Comment by Rafiot** [comment]
Should be fixed, can you give a try?

**Comment by cyber-guy** [comment]
Works perfectly now, thank you!
